name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # 安装 NuGet
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    # 还原 NuGet 包
    - name: NuGet restore
      run: nuget restore
      
    # 添加 MSBuild.exe 到环境变量: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    # 编译整个项目
    - name: Build the solution
      run: |
        msbuild -t:restore
        msbuild /p:Configuration=Release /p:Platform="Any CPU"
      env:
        Configuration: ${{ matrix.configuration }}
        
    # 上传编译成品
    - name: Upload to artifact
      uses: actions/upload-artifact@main
      with:
        name: Aurora-Chat-Bot
        path: Aurora-Chat-Bot/bin/Release

    # 发布
    - name: Zip the Build
      run: zip -r ${{ secrets.ReleaseZipName }} ./AuroraChatBot/bin/Release\net8.0-windows/
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          ${{ secrets.ReleaseZipName }}.zip
